// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQYjXDW7LaIlXp3loa3NqN56fJF1p4ICw',
    appId: '1:583984229682:web:016645da032192a8bfbb2b',
    messagingSenderId: '583984229682',
    projectId: 'bioallin-tuapp',
    authDomain: 'bioallin-tuapp.firebaseapp.com',
    storageBucket: 'bioallin-tuapp.appspot.com',
    measurementId: 'G-PCHEXBRVKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0te1neJ4lVCbDGMz5lFC04jqTLxWZIyg',
    appId: '1:583984229682:android:5c51064d15e77b23bfbb2b',
    messagingSenderId: '583984229682',
    projectId: 'bioallin-tuapp',
    storageBucket: 'bioallin-tuapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVgWxyKbr-xSlTqgtnK6SHa7MSQmZuMOo',
    appId: '1:583984229682:ios:2222d68e23500df4bfbb2b',
    messagingSenderId: '583984229682',
    projectId: 'bioallin-tuapp',
    storageBucket: 'bioallin-tuapp.appspot.com',
    iosClientId: '583984229682-3mjcmu54q0blcsegi6j4sd6fnn74ccv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.bioallin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVgWxyKbr-xSlTqgtnK6SHa7MSQmZuMOo',
    appId: '1:583984229682:ios:33da14d1b0d8a96fbfbb2b',
    messagingSenderId: '583984229682',
    projectId: 'bioallin-tuapp',
    storageBucket: 'bioallin-tuapp.appspot.com',
    iosClientId: '583984229682-p784fd42ejc9bg3n6014pof01hj2tvkj.apps.googleusercontent.com',
    iosBundleId: 'com.example.bioallin.RunnerTests',
  );
}
